sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bhaskarerumalu/react -f Dockerfile.dev .

script:
  - docker run bhaskarerumalu/react npm run test -- --coverage

