sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t bhaskarerumalu/react -f Dockerfile.dev .

script:
  - docker run -e CI=true bhaskarerumalu/react npm run test

